### ISSUE TITLE
source grid and target grid ranges

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris-agg-regrid#39]
Require to cope with a source grid in the range [-180, 180] and a target grid in the range [0, 360],
otherwise only half the data is regridded :cry:

**Comment by bsherratt** [comment]
This may not just be about *mismatched* ranges, rather just generally not handling modular arithmetic.

I just attempted to use agg-regrid with rotated pole model data as the source, centred around 360 degrees grid_longitude (~350 - 370), and a lambert conic projection as the target (so not even measured in degrees). The result was entirely masked. Until I realised that it could be related to this, and tried subtracting 360 from all longitudes - then it worked fine!

That's OK as a workaround for now, but I'm concerned that the pre-image of a different projection might be [0, 360], in which case we'd lose half the data. Or in general, any range of values that might be equivalent mod 360 to the source grid coordinates, without actually being equal.
